version: "3.8"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./frontend
      network: host
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/code
      - /code/node_modules
  backend:
    build:
      context: .
      network: host
    depends_on:
      - db
    entrypoint: ./docker-entrypoint.sh
    environment:
      DEBUG: "true"
      RUN_FLAG: "DEV"
      DB_LOCATION: "db"
      BROKER_HOST: "broker"
      BROKER_KEY: "redis"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/code
  broker:
    image: redis
    command: >
      --requirepass redis
  samba:
    build: ./samba_test_server
    volumes:
      - ./samba_test_server/shared_files:/Shared
#    ports:
#      - "139:139"
#      - "445:445"
#      - "1433:1433"
